<a href="https://colab.research.google.com/github/gabrielsomulo/Projetos-Alura/blob/main/Pandas_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# CSV

In [ ]:
url_csv1 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'
dados_csv1 = pd.read_csv(url_csv1)

In [ ]:
url_csv2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'
dados_csv2 = pd.read_csv(url_csv2, sep=';')

## Importação seletiva

In [ ]:
dados_linhas_csv1 = pd.read_csv(url_csv1, nrows=5)
dados_linhas_csv1

In [2]:
dados_colunas_csv1 = pd.read_csv(url_csv1, nrows=3, usecols=['Id', 'Year_Birth','Income'])
dados_colunas_csv1

NameError: name 'pd' is not defined

In [ ]:
dados_colunas_index_csv1 = pd.read_csv(url_csv1, nrows=3, usecols=[0, 3,5])
dados_colunas_index_csv1

## Gravação de iformações

In [ ]:
dados_colunas_index_csv1.to_csv('dados_colunas_index_csv1.csv')

In [ ]:
# Sem tratamento de dados
coleta_de_dados_com_index = pd.read_csv('dados_colunas_index_csv1.csv')
coleta_de_dados_com_index

In [ ]:
# Com tratamento de dados
dados_colunas_index_csv1.to_csv('dados_colunas_index_csv1.csv', index=False)
coleta_de_dados_sem_index = pd.read_csv('dados_colunas_index_csv1.csv')
coleta_de_dados_sem_index

## Exercícios da Aula 01

In [ ]:
url_saude = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'
ISO = 'ISO-8859-1'

In [ ]:
dados_saude = pd.read_csv(url_saude, encoding= ISO, sep=';', nrows = 5, usecols = [0,159,160], skiprows=3, engine='python')
#dados_saude = pd.read_csv(url_saude, encoding= ISO, sep=';', skiprows=3, skipfooter = 9, engine='python')
dados_saude

# Excel

In [ ]:
url_excel1 = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [ ]:
dados_excel1 = pd.read_excel(url_excel1)

## Escolha de página

In [ ]:
pd.ExcelFile(url_excel1).sheet_names

In [3]:
dados_emissoes_excel = pd.read_excel(url_excel1, sheet_name='emissoes_C02')
dados_emissoes_percapita_excel = pd.read_excel(url_excel1, sheet_name='emissoes_percapita')
dados_fontes_excel = pd.read_excel(url_excel1, sheet_name='fontes')

NameError: name 'pd' is not defined

## Escolha de coluna

In [ ]:
dados_fontes_excel

In [ ]:
dados_fontes_excel_AC = pd.read_excel(url_excel1, sheet_name='fontes', usecols='A:C')

## Escolha das linhas

In [ ]:
dados_fontes_excel_AC_10 = pd.read_excel(url_excel1, sheet_name='fontes', usecols='A:C', nrows=10)

In [ ]:
dados_fontes_excel_AC_10

## Salvamento do projeto

In [ ]:
dados_fontes_excel_AC_10.to_excel('dados_fontes_excel_AC_10.xlsx', index=False)

In [ ]:
dados_importados_excel = pd.read_excel('dados_fontes_excel_AC_10.xlsx')
dados_importados_excel

## Tratamento com Google planilhas

In [ ]:
url_google_planilhas = 'https://docs.google.com/spreadsheets/d/10RXxBCL_7O715c7awgU4LpKXjg9nKfv_Wf6Xij2ebK0/edit?usp=sharing'

In [ ]:
google_planilhas_id = '10RXxBCL_7O715c7awgU4LpKXjg9nKfv_Wf6Xij2ebK0'

In [ ]:
url_google_planilhas_completo = f'https://docs.google.com/spreadsheets/d/{google_planilha_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
dados_fontes_google_planilhass = pd.read_csv(url_google_planilhas_completo)
dados_fontes_google_planilhass

In [ ]:
google_planilhas_pagina = '2'
google_planilhas_url = url_google_planilhas_completo + f'={google_planilhas_pagina}'

In [ ]:
dados_fontes_2_google_planilhas = pd.read_csv(google_planilhas_url)

In [ ]:
dados_fontes_2_google_planilhas

# JSON

In [5]:
dados_pacientes_JSON = pd.read_json('https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes.json')

In [6]:
dados_pacientes_2_JSON = pd.read_json('https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes_2.json')

## Normalização de dados

In [48]:
dados_pacientes_2_JSON

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

In [49]:
data_frame_normalizado_pacientes_2 = pd.json_normalize(dados_pacientes_2_JSON['Pacientes'])

In [50]:
data_frame_normalizado_pacientes_2

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

## Salvando dados normalizados

In [20]:
dados_pacientes_JSON.to_json('dados_pacientes_JSON.json', index=False)

In [21]:
dados_pacientes_2_JSON.to_json('dados_pacientes_2_JSON.json', index=False)

In [19]:
data_frame_normalizado_pacientes_2.to_json('historico_pacientes.json')

## APIs JSON

In [25]:
import requests
import json

In [29]:
dados_usuarios_cru = requests.get('https://jsonplaceholder.typicode.com/users')

In [30]:
resultado = json.loads(dados_usuarios_cru.text)

Ao usar o argumento sep=' _ ' no método pd.json_normalize, você garante que os subcampos de dados aninhados sejam desaninhados com os níveis unidos por um sublinhado ( _ ). Isso facilita o acesso e a manipulação dos dados no DataFrame, mantendo uma estrutura mais clara.

In [46]:
dados_usuarios_normalizado = pd.json_normalize(resultado, sep='_')

In [47]:
dados_usuarios_normalizado

,id,name,username,email,phone,website,address_street,address_suite,address_city,address_zipcode,address_geo_lat,address_geo_lng,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

# HTML