<a href="https://colab.research.google.com/github/gabrielsomulo/Projetos-Alura/blob/main/Pandas_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# CSV

In [5]:
url_csv1 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'
dados_csv1 = pd.read_csv(url_csv1)

In [6]:
url_csv2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'
dados_csv2 = pd.read_csv(url_csv2, sep=';')

## Importação seletiva

In [7]:
dados_linhas_csv1 = pd.read_csv(url_csv1, nrows=5)
dados_linhas_csv1

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [8]:
dados_colunas_csv1 = pd.read_csv(url_csv1, nrows=3, usecols=['Id', 'Year_Birth','Income'])
dados_colunas_csv1

      Id  Year_Birth  Income
0   1826        1970   84835
1      1        1961   57091
2  10476        1958   67267

In [9]:
dados_colunas_index_csv1 = pd.read_csv(url_csv1, nrows=3, usecols=[0, 3,5])
dados_colunas_index_csv1

      Id Marital_Status  Kidhome
0   1826       Divorced        0
1      1         Single        0
2  10476        Married        0

## Gravação de iformações

In [11]:
dados_colunas_index_csv1.to_csv('dados_colunas_index_csv1.csv')

In [12]:
# Sem tratamento de dados
coleta_de_dados_com_index = pd.read_csv('dados_colunas_index_csv1.csv')
coleta_de_dados_com_index

   Unnamed: 0     Id Marital_Status  Kidhome
0           0   1826       Divorced        0
1           1      1         Single        0
2           2  10476        Married        0

In [15]:
# Com tratamento de dados
dados_colunas_index_csv1.to_csv('dados_colunas_index_csv1.csv', index=False)
coleta_de_dados_sem_index = pd.read_csv('dados_colunas_index_csv1.csv')
coleta_de_dados_sem_index

      Id Marital_Status  Kidhome
0   1826       Divorced        0
1      1         Single        0
2  10476        Married        0

## Exercícios da Aula 01

In [45]:
url_saude = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'
ISO = 'ISO-8859-1'

In [58]:
dados_saude = pd.read_csv(url_saude, encoding= ISO, sep=';', nrows = 5, usecols = [0,159,160], skiprows=3, engine='python')
#dados_saude = pd.read_csv(url_saude, encoding= ISO, sep=';', skiprows=3, skipfooter = 9, engine='python')
dados_saude

  Unidade da Federação     2021/Mar          Total
0             Rondônia  11023309,47   996411254,68
1                 Acre   4077045,92   450048530,47
2             Amazonas  22032176,22  1917247936,05
3              Roraima   3985530,08   328876965,09
4                 Pará  33276392,89  4705309002,29

# Excel