<a href="https://colab.research.google.com/github/gabrielsomulo/Projetos-Alura/blob/main/Pandas_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# CSV

In [ ]:
url_csv1 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'
dados_csv1 = pd.read_csv(url_csv1)

In [ ]:
url_csv2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'
dados_csv2 = pd.read_csv(url_csv2, sep=';')

## Importação seletiva

In [ ]:
dados_linhas_csv1 = pd.read_csv(url_csv1, nrows=5)
dados_linhas_csv1

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
dados_colunas_csv1 = pd.read_csv(url_csv1, nrows=3, usecols=['Id', 'Year_Birth','Income'])
dados_colunas_csv1

      Id  Year_Birth  Income
0   1826        1970   84835
1      1        1961   57091
2  10476        1958   67267

In [ ]:
dados_colunas_index_csv1 = pd.read_csv(url_csv1, nrows=3, usecols=[0, 3,5])
dados_colunas_index_csv1

      Id Marital_Status  Kidhome
0   1826       Divorced        0
1      1         Single        0
2  10476        Married        0

## Gravação de iformações

In [ ]:
dados_colunas_index_csv1.to_csv('dados_colunas_index_csv1.csv')

In [ ]:
# Sem tratamento de dados
coleta_de_dados_com_index = pd.read_csv('dados_colunas_index_csv1.csv')
coleta_de_dados_com_index

   Unnamed: 0     Id Marital_Status  Kidhome
0           0   1826       Divorced        0
1           1      1         Single        0
2           2  10476        Married        0

In [ ]:
# Com tratamento de dados
dados_colunas_index_csv1.to_csv('dados_colunas_index_csv1.csv', index=False)
coleta_de_dados_sem_index = pd.read_csv('dados_colunas_index_csv1.csv')
coleta_de_dados_sem_index

      Id Marital_Status  Kidhome
0   1826       Divorced        0
1      1         Single        0
2  10476        Married        0

## Exercícios da Aula 01

In [ ]:
url_saude = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'
ISO = 'ISO-8859-1'

In [ ]:
dados_saude = pd.read_csv(url_saude, encoding= ISO, sep=';', nrows = 5, usecols = [0,159,160], skiprows=3, engine='python')
#dados_saude = pd.read_csv(url_saude, encoding= ISO, sep=';', skiprows=3, skipfooter = 9, engine='python')
dados_saude

  Unidade da Federação     2021/Mar          Total
0             Rondônia  11023309,47   996411254,68
1                 Acre   4077045,92   450048530,47
2             Amazonas  22032176,22  1917247936,05
3              Roraima   3985530,08   328876965,09
4                 Pará  33276392,89  4705309002,29

# Excel

In [3]:
url_excel1 = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [5]:
dados_excel1 = pd.read_excel(url_excel1)

## Escolha de página

In [6]:
pd.ExcelFile(url_excel1).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [9]:
dados_emissoes_excel = pd.read_excel(url_excel1, sheet_name='emissoes_C02')
dados_emissoes_percapita_excel = pd.read_excel(url_excel1, sheet_name='emissoes_percapita')
dados_fontes_excel = pd.read_excel(url_excel1, sheet_name='fontes')

## Escolha de coluna

In [10]:
dados_fontes_excel

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

In [16]:
dados_fontes_excel_AC = pd.read_excel(url_excel1, sheet_name='fontes', usecols='A:C')

## Escolha das linhas

In [14]:
dados_fontes_excel_AC_10 = pd.read_excel(url_excel1, sheet_name='fontes', usecols='A:C', nrows=10)

In [15]:
dados_fontes_excel_AC_10

          País ISO 3166-1 alpha-3   Ano
0  Afeganistão                AFG  1750
1  Afeganistão                AFG  1751
2  Afeganistão                AFG  1752
3  Afeganistão                AFG  1753
4  Afeganistão                AFG  1754
5  Afeganistão                AFG  1755
6  Afeganistão                AFG  1756
7  Afeganistão                AFG  1757
8  Afeganistão                AFG  1758
9  Afeganistão                AFG  1759

## Salvamento do projeto

In [18]:
dados_fontes_excel_AC_10.to_excel('dados_fontes_excel_AC_10.xlsx', index=False)

In [19]:
dados_importados_excel = pd.read_excel('dados_fontes_excel_AC_10.xlsx')
dados_importados_excel

          País ISO 3166-1 alpha-3   Ano
0  Afeganistão                AFG  1750
1  Afeganistão                AFG  1751
2  Afeganistão                AFG  1752
3  Afeganistão                AFG  1753
4  Afeganistão                AFG  1754
5  Afeganistão                AFG  1755
6  Afeganistão                AFG  1756
7  Afeganistão                AFG  1757
8  Afeganistão                AFG  1758
9  Afeganistão                AFG  1759

## Tratamento com Google planilhas

In [43]:
url_google_planilhas = 'https://docs.google.com/spreadsheets/d/10RXxBCL_7O715c7awgU4LpKXjg9nKfv_Wf6Xij2ebK0/edit?usp=sharing'

In [49]:
google_planilhas_id = '10RXxBCL_7O715c7awgU4LpKXjg9nKfv_Wf6Xij2ebK0'

In [50]:
url_google_planilhas_completo = f'https://docs.google.com/spreadsheets/d/{google_planilha_id}/gviz/tq?tqx=out:csv&sheet'

In [51]:
dados_fontes_google_planilhass = pd.read_csv(url_google_planilhas_completo)
dados_fontes_google_planilhass

,index,País,ISO 3166-1 alpha-3,Ano,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,Afeganistão,AFG,1755,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,Afeganistão,AFG,1756,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,Afeganistão,AFG,1757,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,Afeganistão,AFG,1758,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Afeganistão,AFG,1759,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
google_planilhas_pagina = '2'
google_planilhas_url = url_google_planilhas_completo + f'={google_planilhas_pagina}'

In [53]:
dados_fontes_2_google_planilhas = pd.read_csv(google_planilhas_url)

In [54]:
dados_fontes_2_google_planilhas

   index    País ISO 3166-1 alpha-3   Ano
0      0  Brasil                BRL  2000
1      1  Brasil                BRL  2000
2      2  Brasil                BRL  2000
3      3  Brasil                BRL  2000
4      4  Brasil                BRL  2000
5      5  Brasil                BRL  2000
6      6  Brasil                BRL  2000
7      7  Brasil                BRL  2000
8      8  Brasil                BRL  2000
9      9  Brasil                BRL  2000